<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>OmniTTS.Shared</Title>
    <Version />
    <Authors>HickoryTrail</Authors>
    <Product>OmniTTS</Product>
    <PackageProjectUrl>https://github.com/HickoryTrail/OmniTTS/blob/master/OmniTTS.Shared</PackageProjectUrl>
    <PackageIcon>Logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>text-to-speech;tool;tts;classisland</PackageTags>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>LGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\assests\Logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
