<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <ClassIslandPluginSdkVersion>1.7.106.2-dev-v2</ClassIslandPluginSdkVersion>
        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    </PropertyGroup>

    <PropertyGroup Label="Avalonia">
      <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
      <AvaloniaXamlIlDebuggerLaunch>True</AvaloniaXamlIlDebuggerLaunch>
      <AvaloniaXamlCreateSourceInfo>True</AvaloniaXamlCreateSourceInfo>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClassIsland.PluginSdk" Version="2.1.0.1">
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="RestSharp" Version="114.0.0" />
        <PackageReference Include="OpenAI" Version="2.12.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OmniTTS.Shared\OmniTTS.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
